name: GitHub Actions for linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
            - main
            - 'releases/**'
    pull_request:
        branches:
            - main
            - 'releases/**'
jobs:
    piplene:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Startin Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build production project
              run: npm run build:prod
            - name: linting type script
              run: npm run lint:ts
            - name: linting scss
              run: npm run lint:scss
            - name: unit testing
              run: npm run test:unit
            - name: build storybook
              run: npm run storybook:build
